### ISSUE TITLE
Does the framework support the latest version of symsan?

### ISSUE THREAD

**Issue by qhjchc** [chenju2k6/magma#1]
Hi there,

I try to run the `symsan` and `symsan_sec` in different projects but all face the following issues:

```
Compiling fastgen v0.1.0 (/magma/fuzzers/symsan/symsan/fuzzer)
error: failed to run custom build command for `fastgen v0.1.0 (/magma/fuzzers/symsan/symsan/fuzzer)`

Caused by:
  process didn't exit successfully: `/magma/fuzzers/symsan/symsan/target/debug/build/fastgen-fdb3ceb30c3a18e6/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'protoc binary not found: cannot find binary path', /home/.cargo/registry/src/github.com-1ecc6299db9ec823/protoc-2.28.0/src/lib.rs:209:17
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
The command '/bin/sh -c ${FUZZER}/fetch.sh && ${FUZZER}/build.sh' returned a non-zero code: 101
```

Should I specify a certain commit id for the `symsan` in $FUZZER/fetch.sh ?

**Comment by chenju2k6** [comment]
Sorry for the late reply. Thanks for your interest in our work. I will take a look today

**Comment by chenju2k6** [comment]
Should be fixed with this commit https://github.com/chenju2k6/magma/commit/a7dd1793c3f9de1461f70a911a57779f87db759d

**Comment by qhjchc** [comment]
Thanks a lot for your help.

I have pulled the latest commit a7dd179, it works on `libpng`, `libtiff`, `poppler` and `libxml2` now :)
However, the framework still failed to build symsan in `sqlite3` and `openssl` with the following issues:

```
#26 724.7 /magma_out/symsantrack/afl_driver.o: In function `main':
#26 724.7 /magma/fuzzers/symsan_sec/afl/afl_driver.cpp:56: undefined reference to `dfs$_Znam'
#26 724.7 /magma/fuzzers/symsan_sec/afl/afl_driver.cpp:59: undefined reference to `dfs$_ZdaPv'
#26 724.7 clang: error: linker command failed with exit code 1 (use -v to see invocation)
#26 ERROR: process "/bin/sh -c ${FUZZER}/instrument.sh" did not complete successfully: exit code: 1
------
 > [22/22] RUN /magma/fuzzers/symsan_sec/instrument.sh:
------
process "/bin/sh -c ${FUZZER}/instrument.sh" did not complete successfully: exit code: 1
```

```
#26 86.81 clang: error: linker command failed with exit code 1 (use -v to see invocation)
#26 86.81 utils/CMakeFiles/pdfimages.dir/build.make:179: recipe for target 'utils/pdfimages' failed
#26 86.81 make[3]: *** [utils/pdfimages] Error 1
#26 86.81 make[2]: *** [utils/CMakeFiles/pdfimages.dir/all] Error 2
#26 86.81 CMakeFiles/Makefile2:176: recipe for target 'utils/CMakeFiles/pdfimages.dir/all' failed
#26 86.81 CMakeFiles/Makefile2:188: recipe for target 'utils/CMakeFiles/pdfimages.dir/rule' failed
#26 86.81 make[1]: *** [utils/CMakeFiles/pdfimages.dir/rule] Error 2
#26 86.81 make: *** [pdfimages] Error 2
#26 86.81 Makefile:201: recipe for target 'pdfimages' failed
#26 ERROR: process "/bin/sh -c ${FUZZER}/instrument.sh" did not complete successfully: exit code: 2
------
 > [22/22] RUN /magma/fuzzers/symsan/instrument.sh:
------
process "/bin/sh -c ${FUZZER}/instrument.sh" did not complete successfully: exit code: 2
```
